# Form implementation generated from reading ui file 'setup_preset.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(247, 260)
        Dialog.setStyleSheet("background: radial-gradient(50% 50% at 50% 50%, rgba(255, 255, 255, 0.17) 0%, rgba(60, 60, 60, 0) 85.42%), #18181B;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 10, 91, 31))
        self.label_5.setStyleSheet("color: #fff;\n"
"font: 8pt \"Yu Gothic UI Semilight\";\n"
"font-size: 14px;")
        self.label_5.setObjectName("label_5")
        self.pushButton_7 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 60, 161, 31))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_7.setStyleSheet("background-color: gray;\n"
"border-radius: 6px;\n"
"opacity: 0.5;\n"
"font-size: 14px;\n"
"color: #fff;")
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Пресеты</span></p></body></html>"))
        self.pushButton_7.setText(_translate("Dialog", "пресет1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
